config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  root to: "static_pages#root"
  # root to: "session#new"

  resource :session, only: [:new, :create, :destroy]
  resource :users, only: [:new, :create]

  namespace :api, defaults: { format: :json } do
    resources :tabs
    resources :users, only: [:create, :show, :index]
    resources :users_friends, only: [:create, :destroy, :show, :index]
    resources :users_tabs
  end
end

app/models/tab.rb
# == Schema Information
#
# Table name: tabs
#
#  id           :integer          not null, primary key
#  user_id      :integer          not null
#  title        :string           not null
#  date         :date             not null
#  total_amount :decimal(6, 2)    default("0")
#  tag          :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Tab < ActiveRecord::Base
  validates :user_id, :title, :date, :total_amount, presence: true

  belongs_to :user
  
  has_many :users_tabs
  has_many :owers, through: :users_tabs, source: :user
end

app/controllers/api/tabs_controller.rb
module Api
  class TabsController < ApplicationController
    before_action :require_log_in

    def new
      render json: {}
    end

    def create
      @tab = Tab.new(tab_params)
      @tab.user_id = current_user.id

      if @tab.save
        render json: @tab
      else
        render json: @tab.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      @tab = Tab.find(params[:id])
      @tab.destroy
      render json: {}
    end

    def show
      @tab = Tab.find(params[:id])

      if current_user.tabs.include?(@tab)
        render :show
      else
        render json: ["You are not an owner or participant of this tab."]
      end
    end

    def index
      @tabs = current_user.tabs
      render :index
    end

    def edit
      @tab = Tab.find(params[:id])
      render json: @tab
    end

    def update
      @tab = Tab.find(params[:id])

      if @tab.update(tab_params)
        render json: @tab
      else
        flash.now[:errors] = @tab.errors.full_messages
        render :edit
      end
    end

    private
    def tab_params
      params.require(:tab).permit(:title, :date, :total_amount, :tag)
    end
  end
end

app/helpers/tabs_helper.rb
module TabsHelper
end

app/views/tabs/edit.html.erb
<h1>Edit Tab</h1>

<form action="/users/<%= current_user.id %>/tabs/<%= @tab.id %>" method="post">
  <input name="_method" type="hidden" value="patch">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <label for="tab_title">Title: </label>
  <input type="text" name="tab[title]" id="tab_title" value="<%= @tab.title %>">
  <br>
  <label for="tab_tag">Tag: </label>
  <input type="text" name="tab[tag]" id="tab_tag" value="<%= @tab.tag %>">
  <br>

  <label for="tab_date">Date: </label>
  <input type="date" name="tab[date]" id="tab_date" value="<%= @tab.date %>">
  <br>

  <label for="tab_total_amount">Total Amount: </label>
  <input type="text" name="tab[total_amount]" id="tab_total_amount" value="<%= @tab.total_amount %>">
  <br>

  <input type="submit" value="Update Tab">
</form>

app/views/tabs/index.html.erb
<h2>All Your Tabs</h2>
<ul>
  <% @tabs.each do |tab| %>
    <li><%= tab.title %></li>
  <% end %>
</ul>

app/views/tabs/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <ul>
      <li><%= error %></li>
    </ul>
  <% end %>
<% end %>

<h1>Create New Tab</h1>

<form action="/users/<%= current_user.id %>/tabs" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <label for="tab_title">Title: </label>
  <input type="text" name="tab[title]" id="tab_title">
  <br>
  <label for="tab_tag">Tag: </label>
  <input type="text" name="tab[tag]" id="tab_tag">
  <br>

  <label for="tab_date">Date: </label>
  <input type="date" name="tab[date]" id="tab_date">
  <br>

  <label for="tab_total_amount">Total Amount: </label>
  <input type="text" name="tab[total_amount]" id="tab_total_amount">
  <br>

  <input type="submit" value="Create New Tab">
</form>

app/views/tabs/show.html.erb
<h1><%= @tab.title %></h1>
<ul>
  <li>Date: <%= @tab.date %></li>
  <li>Tag: <%= @tab.tag %></li>
  <li>Total amount: $<%= @tab.total_amount %></li>
</ul>

<%= button_to "Delete Tab", "/users/#{current_user.id}/tabs/#{@tab.id}", method: :delete %>
<%= link_to "Edit Tab", edit_user_tab_url(current_user, @tab) %>